config/routes.rb
Rails.application.routes.draw do
  resources :surveys
    root 'surveys#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/survey.rb
class Survey < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ]

  # GET /surveys or /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully created." }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:name, :laptop, :os)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey4400</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/surveys/_form.html.erb
<%= form_with(model: survey) do |form| %>
  <% if survey.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :"Enter Your Name", style: "display: block", class: "form-control" %>
    <%= form.text_area :name %>
  </div>

  <div class="form-group">
    <%= form.label :laptop, "Do you own a laptop?" %><br />
    <%= form.label :laptop, "Yes", :value => "true" %>
    <%= form.radio_button :laptop, 'yes' %>
    <%= form.label :laptop, "No", :value => "false" %>
    <%= form.radio_button :laptop, 'No' %>
  </div>

  <div class="form-group">
    <%= form.select :os, ['No OS', 'Mac OSX', 'Windows 10', 'Windows 7 or below', 'Linux']%>
  </div>

  <div class="form-group">
    <%= form.submit "Submit Your Response", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/surveys/_survey.html.erb
<div id="<%= dom_id survey %>">
  <p>
    <strong>Name:</strong>
    <%= survey.name %>
  </p>

  <p>
    <strong>Laptop:</strong>
    <%= survey.laptop %>
  </p>

  <p>
    <strong>Os:</strong>
    <%= survey.os %>
  </p>

</div>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render "form", survey: @survey %>

<br>

<div>
  <%= link_to "Show this survey", @survey %> |
  <%= link_to "Back to surveys", surveys_path %>
</div>

app/views/surveys/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Surveys</h1>

<div id="surveys" class="table" table-striped>
  <% @surveys.each do |survey| %>
    <%= render survey %>
    <p>
      <%= link_to "Show this survey", survey %>
    </p>
  <% end %>
</div>

<%= link_to "New survey", new_survey_path %>

app/views/surveys/new.html.erb
<div class="container">

  <h1>New survey</h1>

  <%= render "form", survey: @survey %>

  <br>

  <div>
    <%= link_to "Back to surveys", surveys_path %>
  </div>

</div>

app/views/surveys/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @survey %>

  <div>
    <%= link_to "Edit this survey", edit_survey_path(@survey) %> |
    <%= link_to "Back to surveys", surveys_path %>

    <%= button_to "Destroy this survey", @survey, method: :delete %>
  </div>

</div>